Dezhong Shen


In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
%matplotlib inline

data = pd.read_csv("./wiki_movie_plots_deduped.csv")
data.head()

Release Year                             Title Origin/Ethnicity  \
0          1901            Kansas Saloon Smashers         American   
1          1901     Love by the Light of the Moon         American   
2          1901           The Martyred Presidents         American   
3          1901  Terrible Teddy, the Grizzly King         American   
4          1902            Jack and the Beanstalk         American   

                             Director Cast    Genre  \
0                             Unknown  NaN  unknown   
1                             Unknown  NaN  unknown   
2                             Unknown  NaN  unknown   
3                             Unknown  NaN  unknown   
4  George S. Fleming, Edwin S. Porter  NaN  unknown   

                                           Wiki Page  \
0  https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...   
1  https://en.wikipedia.org/wiki/Love_by_the_Ligh...   
2  https://en.wikipedia.org/wiki/The_Martyred_Pre...   
3  https://en.wikipedia.org/wiki/Terrible_Teddy,_...   
4  https://en.wikipedia.org/wiki/Jack_and_the_Bea...   

                                                Plot  
0  A bartender is working at a saloon, serving dr...  
1  The moon, painted with a smiling face hangs ov...  
2  The film, just over a minute long, is composed...  
3  Lasting just 61 seconds and consisting of two ...  
4  The earliest known adaptation of the classic f...

In [2]:
data['Genre'].count()

34886

In [3]:
#get the proportion of each class in the data set
(data['Genre'].value_counts()/data['Genre'].count())*100

unknown                                        17.436794
drama                                          17.095683
comedy                                         12.552313
horror                                          3.345181
action                                          3.147394
thriller                                        2.769019
romance                                         2.645760
western                                         2.479505
crime                                           1.628160
adventure                                       1.507768
musical                                         1.338646
crime drama                                     1.330046
romantic comedy                                 1.321447
science fiction                                 1.198188
film noir                                       0.988935
mystery                                         0.888609
war                                             0.782549
animation                      

Clean the text:
● Remove stop words
● Remove numbers and other non-letter characters
● Stem the words

In [4]:
#select the 5 classes we need
data1=data[data['Genre'].isin(['drama','comedy','adventure','romance','western'])]
data1

Release Year                                     Title  \
6              1903                   The Great Train Robbery   
7              1904                           The Suburbanite   
14             1907           How Brown Saw the Baseball Game   
15             1907                              Laughing Gas   
16             1908                  The Adventures of Dollie   
17             1908                           The Black Viper   
18             1908                    A Calamitous Elopement   
19             1908                      The Call of the Wild   
20             1908                         A Christmas Carol   
21             1908                     The Fight for Freedom   
22             1909                              At the Altar   
23             1909                  A Drunkard's Reformation   
24             1909                          The Golden Louis   
26             1910                          An Arcadian Maid   
29             1910               Hemlock Hoax, the Detective   
30             1910            The House with Closed Shutters   
31             1910                    A Lad from Old Ireland   
33             1910                                    Ramona   
37             1911  The Black Arrow: A Tale of the Two Roses   
38             1911                          Brown of Harvard   
40             1911                         David Copperfield   
42             1911                            Sweet Memories   
46             1912               The Musketeers of Pig Alley   
48             1912                            Petticoat Camp   
49             1912                 Put Yourself in His Place   
52             1913         Barney Oldfield's Race for a Life   
53             1913                                Bob's Baby   
54             1913                      Cohen Saves the Flag   
57             1913                    The Face at the Window   
58             1913                             The Quakeress   
...             ...                                       ...   
34842          2010                            Recep İvedik 3   
34843          2010                               Eyvah Eyvah   
34844          2010                            Eşrefpaşalılar   
34847          2010                                 Ay Lav Yu   
34848          2010                         Dersimiz: Atatürk   
34849          2010                        Black Dogs Barking   
34850          2010                         Men on the Bridge   
34851          2010              Çok Berbat Hareketler Bunlar   
34852          2010                                     Honey   
34853          2010                           Black and White   
34854          2010                  Selvi Boylum Al Yazmalım   
34855          2010                                      Haze   
34856          2010                  A Step into the Darkness   
34857          2010                              How Are You?   
34858          2010                              The Crossing   
34860          2010                                    Jackal   
34862          2010                              Other Angels   
34863          2010                                 Hayde Bre   
34864          2011                            Eyyvah Eyvah 2   
34865          2011                                  Free Man   
34867          2011                                 Scapegoat   
34868          2011                   Love Likes Coincidences   
34870          2011                                     Press   
34871          2011                            Merry-Go-Round   
34873          2011                                Toll Booth   
34874          2011                             White as Snow   
34875          2011              Once Upon a Time in Anatolia   
34876          2013                                     Selam   
34882          2017                        Çalgı Çengi İkimiz   
34883          2017                       

In [5]:
#Plan to use 'Plot' to do the prediction and classification
df=data1[['Plot','Genre']]
df

Plot      Genre
6      The film opens with two bandits breaking into ...    western
7      The film is about a family who move to the sub...     comedy
14     Before heading out to a baseball game at a nea...     comedy
15     The plot is that of a black woman going to the...     comedy
16     On a beautiful summer day a father and mother ...      drama
17     A thug accosts a girl as she leaves her workpl...      drama
18     A young couple decides to elope after being ca...     comedy
19     A white girl (Florence Lawrence) rejects a pro...  adventure
20     No prints of the first American film adaptatio...      drama
21     The film opens in a town on the Mexican border...    western
22     A rejected admirer sets up a trap to kill his ...      drama
23     John Wharton, the husband of a true and trusti...      drama
24     An old woman sends a girl begging in the stree...      drama
26     Mary Pickford plays Priscilla an unemployed ma...      drama
29     Hemlock Hoax is a detective who has little res...     comedy
30     During the American Civil War a young soldier ...      drama
31     An Irish boy (Olcott) emigrates to America to ...      drama
33     Ramona chronicles the romance between Ramona (...      drama
37     The novel is set in the reign of "old King Hen...      drama
38     The story deals with Tom Brown's efforts to sa...      drama
40     "David Copperfield consists of three reels and...      drama
42     Polly Biblett (Mary Pickford), a young lady, t...      drama
46     The film is about a poor married couple living...      drama
48     Only lasting 15 minutes, it is a light-hearted...     comedy
49     The story is of an English manufacturing town ...      drama
52     Barney Oldfield races a speeding locomotive to...     comedy
53     Bob, a typically devoted husband, is told by h...     comedy
54     Cohen (Ford Sterling) and his rival Goldberg (...     comedy
57     As described in a 1913 blurb: "The foreman of ...      drama
58     The setting is an early American village, wher...      drama
...                                                  ...        ...
34842  Recep İvedik (Şahan Gökbakar) shows signs of d...     comedy
34843  Hüseyin (Ata Demirer) is a young man living wi...     comedy
34844  The film is about two friends, Tayyar (Hüseyin...      drama
34847  Yusuf Ağa, the landlord of the tiny southeast ...     comedy
34848  A group of primary school students are assigne...      drama
34849  Selim’s family has migrated from Anatolia to İ...      drama
34850  Fikret (Fikret Portakal) earns a living by sel...      drama
34851  Nine separate stories intertwine into one come...     comedy
34852  In the remote and undeveloped eastern Black Se...      drama
34853  A painter who has lived a stormy life that sti...      drama
34854  İlyas (Kadir İnanır) is a truck driver from İs...      drama
34855  Reşat, a withdrawn and asocial young man who w...      drama
34856  The film tells the tragic story of an Iraqi-Tu...      drama
34857  Semahat, whose parents emigrated to İstanbul f...      drama
34858  Güven works at an accounting firm and leads an...      drama
34860  The life of Akın, who lives in one of the poor...      drama
34862  Sanem (Didem Soylu) is a prostitute who shares...      drama
34863  Şaban Agha (Şevket Emrulla) lives in a small M...      drama
34864  Hüseyin (Ata Demirer), a clarinetist from a vi...     comedy
34865  Muslim Kurdish scholar Said Nursî passes throu...      drama
34867  Şahin K. is a wealthy and famous (or, rather, ...     comedy
34868  One September morning in 1977 in Ankara, a you...      drama
34870  It is the early 1990s, and a handful of journa...      drama
34871  Erdem and Sevil live in a small town with thei...      drama
34873  Kenan is a 35-year-old toll booth attendant st...      drama
34874  Hasan is a twelve-year-old boy living with his...      drama
34875  Through the night, three cars carry a small gr...      drama
34876  The film opens with a Senegalese 

In [6]:
#Remove stop words
#Remove numbers and other non-letter characters
#Stem the words
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

stop_words=set(stopwords.words("english"))
remove=re.compile('[^a-zA-Z ]', re.UNICODE)
ps=PorterStemmer()

newplot=[]
for w in df['Plot']:
    m=remove.sub('', w)
    tokenized_word=word_tokenize(m)
    #newsent=[]
    newsent=""
    for a in tokenized_word:
        if a not in stop_words:
            #newsent.append(ps.stem(a))
            newsent=newsent+ps.stem(a)+" "
    newplot.append(newsent)


In [7]:
newdf=pd.DataFrame({"Plot":newplot,"Genre":df['Genre']})
newdf

Plot      Genre
6      the film open two bandit break railroad telegr...    western
7      the film famili move suburb hope quiet life th...     comedy
14     befor head basebal game nearbi ballpark sport ...     comedy
15     the plot black woman go dentist toothach given...     comedy
16     On beauti summer day father mother take daught...      drama
17     A thug accost girl leav workplac man rescu the...      drama
18     A young coupl decid elop caught midst romant m...     comedy
19     A white girl florenc lawrenc reject propos ind...  adventure
20     No print first american film adapt A christma ...      drama
21     the film open town mexican border A poker game...    western
22     A reject admir set trap kill sweetheart fianc ...      drama
23     john wharton husband true trust wife father ei...      drama
24     An old woman send girl beg street pari snowi e...      drama
26     mari pickford play priscilla unemploy maid fin...      drama
29     hemlock hoax detect littl respect small tropic...     comedy
30     dure american civil war young soldier lose ner...      drama
31     An irish boy olcott emigr america escap desper...      drama
33     ramona chronicl romanc ramona mari pickford sp...      drama
37     the novel set reign old king henri VI war rose...      drama
38     the stori deal tom brown effort save fianc bla...      drama
40     david copperfield consist three reel three sep...      drama
42     polli biblett mari pickford young ladi tell gr...      drama
46     the film poor marri coupl live new york citi t...      drama
48     onli last minut lightheart comedi battl sex se...     comedy
49     the stori english manufactur town huddersfield...      drama
52     barney oldfield race speed locomot rescu damse...     comedy
53     bob typic devot husband told wife stork paid v...     comedy
54     cohen ford sterl rival goldberg henri lehrman ...     comedy
57     As describ blurb the foreman sawmil misconstru...      drama
58     the set earli american villag young quaker wom...      drama
...                                                  ...        ...
34842  recep vedik ahan gkbakar show sign deep depres...     comedy
34843  hseyin ata demir young man live grandpar villa...     comedy
34844  the film two friend tayyar hseyin soysalan maf...      drama
34847  yusuf Aa landlord tini southeast anatolian vil...     comedy
34848  A group primari school student assign homework...      drama
34849  selim famili migrat anatolia stanbul A naiv yo...      drama
34850  fikret fikret portak earn live sell rose bospo...      drama
34851  nine separ stori intertwin one comedi peopl ex...     comedy
34852  In remot undevelop eastern black sea region si...      drama
34853  A painter live stormi life still rage lawyer f...      drama
34854  lya kadir nanr truck driver stanbul come remot...      drama
34855  reat withdrawn asoci young man work pirat dvd ...      drama
34856  the film tell tragic stori iraqiturkish girl c...      drama
34857  semahat whose parent emigr stanbul sarajevo ma...      drama
34858  gven work account firm lead ordinari life He h...      drama
34860  the life akn live one poorest neighborhood ist...      drama
34862  sanem didem soylu prostitut share flat three t...      drama
34863  aban agha evket emrulla live small macedonian ...      drama
34864  hseyin ata demir clarinetist villag turkey thr...     comedy
34865  muslim kurdish scholar said nur pass three pha...      drama
34867  ahin K wealthi famou rather infam man discont ...     comedy
34868  one septemb morn ankara young man rush pregnan...      drama
34870  It earli hand journalist tri attract world att...      drama
34871  erdem sevil live small town two kid edip sevgi...      drama
34873  kenan yearold toll booth attend still live fat...      drama
34874  hasan twelveyearold boy live two younger sibl ...      drama
34875  through night three car carri small group men ...      drama
34876  the film open senegales boy name 

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect=CountVectorizer()
counts=count_vect.fit_transform(newdf['Plot'])
counts.shape

(12657, 90630)

In [9]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer=TfidfTransformer()
df_tdidf=tfidf_transformer.fit_transform(counts)
df_tdidf.shape

(12657, 90630)

In [10]:
df_tdidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Split the data randomly into training and testing set

In [11]:
from sklearn.model_selection import train_test_split 

train, test = train_test_split(newdf,test_size = 0.3)


In [12]:
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import confusion_matrix

c_vect=CountVectorizer()
c=c_vect.fit_transform(train.Plot)
c.shape

(8859, 72664)

In [13]:
t_transformer=TfidfTransformer()
X_train_t=t_transformer.fit_transform(c)
X_train_t.shape

(8859, 72664)

Train SVM and report confusion matrix

In [14]:
svm=Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3,  random_state=42)),])
svm=svm.fit(train.Plot, train.Genre)

pre1=svm.predict(test.Plot)
accuracy_score(test.Genre, pre1)


/Users/itachi/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


0.6158504476040021

In [15]:
confusion_matrix(test.Genre, pre1)

array([[  12,   21,  141,    0,    2],
       [   0,  511,  832,    2,    8],
       [   0,   73, 1660,    1,    2],
       [   0,   12,  279,    1,    0],
       [   0,    6,   80,    0,  155]])

Train Multinomial NB and report confusion matrix.

In [16]:
clf=MultinomialNB().fit(X_train_t, train.Genre)

In [17]:
nb=Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf', MultinomialNB()),])
nb=nb.fit(train.Plot, train.Genre)

pre2=nb.predict(test.Plot)
accuracy_score(test.Genre, pre2)

0.4873617693522907

In [18]:
confusion_matrix(test.Genre, pre2)

array([[   0,    2,  174,    0,    0],
       [   0,  121, 1232,    0,    0],
       [   0,    6, 1730,    0,    0],
       [   0,    0,  292,    0,    0],
       [   0,    2,  239,    0,    0]])

SVM has the higher accuracy.
Reason:
Naive Bayes treats the data as independent, whereas SVM looks at the interactions between data to a certain degree. In this case, there are relationships between words. So SVM is better in this case.

In [19]:
new_svm=Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3,  random_state=100)),])
new_svm=new_svm.fit(train.Plot, train.Genre)

pre3=new_svm.predict(test.Plot)
accuracy_score(test.Genre, pre3)


/Users/itachi/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


0.6179568193786203

In [20]:
confusion_matrix(test.Genre, pre3)

array([[  12,   23,  140,    0,    1],
       [   0,  526,  816,    2,    9],
       [   0,   83, 1650,    1,    2],
       [   0,   14,  277,    1,    0],
       [   0,    6,   77,    0,  158]])

change the kernel of the SVM does not change the accuracy

In [22]:
#extract the nouns
np1=[]
for w in df['Plot']:
    tokens=word_tokenize(w)
    posd=nltk.pos_tag(tokens)
    is_noun = lambda pos: pos[:2] == 'NN'
    nouns=[word for (word, pos) in posd if is_noun(pos)]
    nn=""
    for n in nouns:
        nn=nn+n+" "
    np1.append(nn)

In [23]:
#get the new data
newdf1=pd.DataFrame({"Plot":np1,"Genre":df['Genre']})
newdf1.head()

Plot    Genre
6   film bandits railroad telegraph office operato...  western
7   film family suburbs life Things wife crockery ...   comedy
14  baseball game ballpark sports Mr. Brown highba...   comedy
15  plot woman dentist toothache gas way walking h...   comedy
16  summer day father mother daughter Dollie outin...    drama

split the new data into train and test

In [24]:
train1, test1 = train_test_split(newdf1,test_size = 0.3)

In [25]:
count_vect1=CountVectorizer()
count1=count_vect1.fit_transform(train1.Plot)
count1.shape

(8859, 52814)

In [26]:
t_transformer1=TfidfTransformer()
X_train_t1=t_transformer1.fit_transform(count1)
X_train_t1.shape

(8859, 52814)

Train a new SVM and report confusion matrix

In [27]:
svm1=Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3,  random_state=42)),])
svm1=svm1.fit(train1.Plot, train1.Genre)
newpre1=svm1.predict(test1.Plot)
accuracy_score(test1.Genre, newpre1)


0.6140073723012112

In [28]:
confusion_matrix(test1.Genre, newpre1)

array([[  21,   18,  125,    0,    3],
       [   3,  504,  788,    2,    4],
       [   2,  159, 1657,    3,    8],
       [   0,   16,  239,    5,    0],
       [   0,    8,   88,    0,  145]])

Train Multinomial NB and report confusion matrix.

In [29]:
clf1=MultinomialNB().fit(X_train_t1, train1.Genre)
nb1=Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf', MultinomialNB()),])
nb1=nb1.fit(train1.Plot, train1.Genre)

newpre2=nb1.predict(test1.Plot)
accuracy_score(test1.Genre, newpre2)

0.5505529225908373

In [30]:
confusion_matrix(test1.Genre, newpre2)

array([[   0,    9,  158,    0,    0],
       [   0,  327,  974,    0,    0],
       [   0,   68, 1761,    0,    0],
       [   0,    5,  255,    0,    0],
       [   0,    8,  230,    0,    3]])

The both results are a little better then the old ones.

The size of the vocabulary is smaller the the old one.